-- Generated by TetView. Wed Jan 21 15:02:41 2009


p=gridgen.tvCreate()
p:create_pt(3801, 2.576397, 10.5, 0.5)
p:create_pt(3827, 2.576397, 10.5, 0)
p:create_pt(3824, 2.8072979999999998, 11, 0)
p:create_pt(107, 2.8072979999999998, 11, 0.5)
p:create_pt(3677, 2.3454959999999998, 10, 0)
p:create_pt(3797, 3, 10.5, 0)

p:draw_subface(3824, 3827, 3801)
p:draw_tet(3827, 3824, 3677, 107)
p:draw_tet(3824, 3827, 3797, 107)
p:set("draw", "geom")
rnd=glvCreate(0, 0, 500, 500, "TetView")
p:plot(rnd)
glvWait()
